apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../base/infra/grafana
patches:
- path: ./helmrelease.grafana.yaml
  target:
    kind: HelmRelease
    name: grafana
